export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAIL = "GET_BOOKS_FAIL";
export const GET_BOOK_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_BOOK_FAIL = "GET_PRODUCT_FAIL";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const SEARCH_BOOKS_FAIL = "SEARCH_BOOKS_FAIL";
export const FILTER_BOOKS_SUCCESS = "FILTER_BOOKS_SUCCESS";
export const FILTER_BOOKS_FAIL = "FILTER_BOOKS_FAIL";

export const GET_AUTHORS_SUCCESS = "GET_AUTHORS_SUCCESS";
export const GET_AUTHORS_FAIL = "GET_AUTHORS_FAIL";
export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
export const GET_AUTHOR_FAIL = "GET_AUTHOR_FAIL";
export const FILTER_AUTHORS_SUCCESS = "FILTER_AUTHORS_SUCCESS";
export const FILTER_AUTHORS_FAIL = "FILTER_AUTHORS_FAIL";
